In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.

# Your code for Task 1 here:



# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
# Create a DataFrame named 'df_sales' with 100 rows and the following columns:
# - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# - 'Sales': Random integers between 100 and 1000.
# - 'Quantity': Random integers between 1 and 10.
# - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.

# Your code for Task 2 here:


# Introduce NaN values



# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# Use 'df_sales' from Task 2.
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.

# Your code for Task 3 here:



# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# Use 'df_sales' from Task 2 (which should have NaNs).
# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.

# Your code for Task 4 here:



# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# Use 'df_sales' (the original one with NaNs)
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
#     Store the result in 'df5_3_grouped_region'.
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
#     Store the result in 'df5_4_grouped_product'.

# Your code for Task 5 here:


--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

--- Task 2: Synthetic Data Generation for Practice ---

--- Task 3: Indexing and Slicing in DataFrames ---

--- Task 4: Data Cleaning (Handling Missing Values) ---

--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---


In [ ]:
# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.

# Your code for Task 1 here:



In [2]:

s1_1 = pd.Series([10, 20, 30, 40, 50])
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("s1_1:")
print(s1_1)
print("\nnp_array1_2:")
print(np_array1_2)
print("\ndf1_3:")
df1_3

s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

np_array1_2:
[[49 78 34 55]
 [87 60  2 22]
 [70 89 74 96]]

df1_3:


A   B   C   D
0  49  78  34  55
1  87  60   2  22
2  70  89  74  96

In [3]:
# prompt: # Task 2: Synthetic Data Generation for Practice
# print("\n--- Task 2: Synthetic Data Generation for Practice ---")
# # Create a DataFrame named 'df_sales' with 100 rows and the following columns:
# # - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# # - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# # - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# # - 'Sales': Random integers between 100 and 1000.
# # - 'Quantity': Random integers between 1 and 10.
# # - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.

dates = pd.date_range(start='2023-01-01', end='2023-04-09', freq='D')
df_sales = pd.DataFrame({
    'Date': np.random.choice(dates, 100),
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100),
    'Quantity': np.random.randint(1, 11, 100)
})

# Introduce NaN values
nan_sales_indices = np.random.choice(df_sales.index, 5, replace=False)
nan_quantity_indices = np.random.choice(df_sales.index, 3, replace=False)

df_sales.loc[nan_sales_indices, 'Sales'] = np.nan
df_sales.loc[nan_quantity_indices, 'Quantity'] = np.nan

print("\ndf_sales (with NaNs):")
df_sales.head()


df_sales (with NaNs):


Date Region  Product  Sales  Quantity
0 2023-04-01  North   Laptop  533.0       6.0
1 2023-03-02   West    Mouse  141.0       2.0
2 2023-03-28   East  Monitor  809.0       4.0
3 2023-03-02   East   Laptop  864.0      10.0
4 2023-02-15  North   Laptop  969.0       7.0

In [4]:
# prompt: # Task 3: Indexing and Slicing in DataFrames
# print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# # Use 'df_sales' from Task 2.
# # 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
# # 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
# # 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
# # 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.
# # Your code for Task 3 here:


df3_1 = df_sales[['Region', 'Sales']]


df3_2 = df_sales[df_sales['Product'] == 'Laptop']


df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]


monitor_sales = df_sales[df_sales['Product'] == 'Monitor']

if not monitor_sales.empty:
    val3_4_loc = monitor_sales.loc[monitor_sales.index[0], 'Sales']
else:
    val3_4_loc = None

# Using .iloc
if not monitor_sales.empty:
    val3_4_iloc = monitor_sales.iloc[0]['Sales']
else:
    val3_4_iloc = None
val3_4 = val3_4_loc


print("\ndf3_1 (Region and Sales columns):")
print(df3_1.head())

print("\ndf3_2 (Rows where Product is Laptop):")
print(df3_2.head())

print("\ndf3_3 (Rows where Region is East and Sales > 500):")
print(df3_3.head())

print(f"\nval3_4 (Sales value for the first Monitor entry using .loc): {val3_4_loc}")
print(f"val3_4 (Sales value for the first Monitor entry using .iloc): {val3_4_iloc}")

val3_4 = val3_4_loc


df3_1 (Region and Sales columns):
  Region  Sales
0  North  533.0
1   West  141.0
2   East  809.0
3   East  864.0
4  North  969.0

df3_2 (Rows where Product is Laptop):
        Date Region Product  Sales  Quantity
0 2023-04-01  North  Laptop  533.0       6.0
3 2023-03-02   East  Laptop  864.0      10.0
4 2023-02-15  North  Laptop  969.0       7.0
7 2023-01-12   West  Laptop  581.0       6.0
9 2023-03-09   West  Laptop  217.0       1.0

df3_3 (Rows where Region is East and Sales > 500):
         Date Region  Product  Sales  Quantity
2  2023-03-28   East  Monitor  809.0       4.0
3  2023-03-02   East   Laptop  864.0      10.0
16 2023-03-23   East   Laptop  812.0       1.0
20 2023-02-28   East    Mouse  515.0       6.0
23 2023-02-19   East   Laptop  747.0       4.0

val3_4 (Sales value for the first Monitor entry using .loc): 809.0
val3_4 (Sales value for the first Monitor entry using .iloc): 809.0


In [5]:
# prompt: # Task 4: Data Cleaning (Handling Missing Values)
# print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# # Use 'df_sales' from Task 2 (which should have NaNs).
# # 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
# # 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
# # 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.
# # Your code for Task 4 here:


missing_counts4_1 = df_sales.isnull().sum()


mean_sales = df_sales['Sales'].mean()
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(mean_sales)


df4_3_dropped = df_sales.dropna()

print("\n4.1 Missing value counts per column:")
print(missing_counts4_1)

print("\n4.2 df_sales after filling missing 'Sales' with mean:")
print(df4_2_filled.head())

print("\n4.3 df_sales after dropping rows with any missing values:")
print(df4_3_dropped.head())


4.1 Missing value counts per column:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

4.2 df_sales after filling missing 'Sales' with mean:
        Date Region  Product  Sales  Quantity
0 2023-04-01  North   Laptop  533.0       6.0
1 2023-03-02   West    Mouse  141.0       2.0
2 2023-03-28   East  Monitor  809.0       4.0
3 2023-03-02   East   Laptop  864.0      10.0
4 2023-02-15  North   Laptop  969.0       7.0

4.3 df_sales after dropping rows with any missing values:
        Date Region  Product  Sales  Quantity
0 2023-04-01  North   Laptop  533.0       6.0
1 2023-03-02   West    Mouse  141.0       2.0
2 2023-03-28   East  Monitor  809.0       4.0
3 2023-03-02   East   Laptop  864.0      10.0
4 2023-02-15  North   Laptop  969.0       7.0


In [6]:
# prompt: # Task 5: Data Manipulation (Columns, Sorting, Grouping)
# print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# # Use 'df_sales' (the original one with NaNs)
# # 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
# #     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
# # 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
# # 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
# #     Store the result in 'df5_3_grouped_region'.
# # 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
# #     Store the result in 'df5_4_grouped_product'.
# # Your code for Task 5 here:


df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])


df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("\n5.1 df_sales with 'Total_Revenue' column:")
print(df_sales.head())

print("\n5.2 df_sales sorted by Date (asc) and Sales (desc):")
print(df5_2_sorted.head())

print("\n5.3 df_sales grouped by Region (sum of Sales and Quantity):")
print(df5_3_grouped_region)

print("\n5.4 df_sales grouped by Product (average Sales):")
df5_4_grouped_product


5.1 df_sales with 'Total_Revenue' column:
        Date Region  Product  Sales  Quantity  Total_Revenue
0 2023-04-01  North   Laptop  533.0       6.0         3198.0
1 2023-03-02   West    Mouse  141.0       2.0          282.0
2 2023-03-28   East  Monitor  809.0       4.0         3236.0
3 2023-03-02   East   Laptop  864.0      10.0         8640.0
4 2023-02-15  North   Laptop  969.0       7.0         6783.0

5.2 df_sales sorted by Date (asc) and Sales (desc):
         Date Region Product  Sales  Quantity  Total_Revenue
85 2023-01-05   West   Mouse  975.0       8.0         7800.0
37 2023-01-05  North  Laptop  373.0       6.0         2238.0
49 2023-01-06   East  Laptop  873.0       5.0         4365.0
51 2023-01-06  North  Laptop  694.0       6.0         4164.0
15 2023-01-06  South   Mouse  302.0       7.0         2114.0

5.3 df_sales grouped by Region (sum of Sales and Quantity):
          Sales  Quantity
Region                   
East    15200.0     115.0
North   15018.0     148.0
South  

Product
Keyboard    695.333333
Laptop      600.928571
Monitor     621.583333
Mouse       524.045455
Name: Sales, dtype: float64